---
  - name: "update apt repo"
    action: apt update_cache=yes

  - name: install python requirements
    action: apt pkg={{ item }} state=installed
    with_items:
      - python-software-properties
      - python-dev
      - python2.7
      - python3.5

  - name: install pip
    action: easy_install name=pip
