---
- name: install Redis server
  apt:
    name: redis-server
    state: latest
    update_cache: yes

- name: check if Redis is running
  service:
    name: redis-server
    state: started

- name: enable redis-server to survive reboot
  service:
    name: redis-server
    enabled: yes
