- job:
    name: ceph-container-build-ceph-base-push-imgs
    node: huge && trusty && x86_64
    project-type: freestyle
    defaults: global
    display-name: 'ceph-container: build and push ceph base container images to Quay.io'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - build-discarder:
          days-to-keep: 1
          num-to-keep: 1
          artifact-days-to-keep: 1
          artifact-num-to-keep: 1
      - github:
          url: https://github.com/ceph/ceph-container

    triggers:
      - timed: '@daily'

    scm:
      - git:
          url: https://github.com/ceph/ceph-container.git
          branches:
            - master
          browser: auto
          basedir: "ceph-container"
          timeout: 20

    builders:
      - shell:
          !include-raw:
            - ../../../scripts/build_utils.sh
            - ../../build/build

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
      - credentials-binding:
          - username-password-separated:
              credential-id: ceph-container-quay-io
              username: REGISTRY_USERNAME
              password: REGISTRY_PASSWORD
