---
jenkins_dest: /opt/jenkins
jenkins_lib: /var/lib/jenkins
jenkins:
  yum:
    #repo: 'deb http://pkg.jenkins-ci.org/debian binary/' # Jenkins repository
    dependencies: # Jenkins dependencies
      #- 'openjdk-7-jre'
      - 'java-1.7.0-openjdk'
      - 'git'
      - 'curl'
      - 'nginx'
  cli_dest: '{{ jenkins_dest }}/jenkins-cli.jar' # Jenkins CLI destination
  updates_dest: '{{ jenkins_dest }}/updates_jenkins.json' # Jenkins updates file
