- project:
    name: ceph-ansible-prs
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - container
      - non_container
    scenario:
      - all_daemons
      - lvm_osds
      - update
      - purge
      - collocation
      - lvm_batch
      - all_in_one
      - external_clients
    jobs:
        - 'ceph-ansible-prs-auto'

- project:
    name: ceph-ansible-prs-ooo
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - ooo_collocation
    jobs:
        - 'ceph-ansible-prs-auto'

- project:
    name: ceph-ansible-prs-podman
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - podman
    jobs:
        - 'ceph-ansible-prs-auto'

- project:
    name: ceph-ansible-prs-auto-switch_to_container
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - non_container
    scenario:
      - switch_to_containers
    jobs:
        - 'ceph-ansible-prs-auto'

- project:
    name: ceph-ansible-prs-docker2podman
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - container
    scenario:
      - docker_to_podman
    jobs:
        - 'ceph-ansible-prs-common-trigger'

- project:
    name: ceph-ansible-prs-common-trigger
    slave_labels: 'vagrant && libvirt && (smithi || braggi || centos7)'
    distribution:
      - centos
    deployment:
      - container
      - non_container
    scenario:
      - add_mdss
      - add_mgrs
      - add_mons
      - add_osds
      - add_rbdmirrors
      - add_rgws
      - rgw_multisite
      - shrink_mon
      - shrink_mgr
      - shrink_osd
      - shrink_osd_legacy
      - shrink_rgw
      - shrink_mds
      - shrink_rbdmirror
      - lvm_auto_discovery
      - filestore_to_bluestore
    jobs:
        - 'ceph-ansible-prs-common-trigger'

- job-template:
    name: 'ceph-ansible-prs-{distribution}-{deployment}-{scenario}'
    id: 'ceph-ansible-prs-auto'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{distribution}-{deployment}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: '^jenkins test {distribution}-{deployment}-{scenario}|jenkins test all.*'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {distribution}-{deployment}-{scenario}"
          started-status: "Running: {distribution}-{deployment}-{scenario}"
          success-status: "OK - {distribution}-{deployment}-{scenario}"
          failure-status: "FAIL - {distribution}-{deployment}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            DISTRIBUTION={distribution}
            DEPLOYMENT={deployment}
            SCENARIO={scenario}
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            # Returns 1 if only .rst and README files were modified
            echo "Checking if only rst and READMEs were modified"
            git show HEAD | grep -qo ^Merge:
            if [ $? -eq 0 ]; then
              git diff --name-only $(git show HEAD | grep ^Merge: | cut -d ':' -f2) | grep -v '\.rst\|README'
              if [ $? -eq 1 ]; then
                echo "Only docs were modified.  Skipping the rest of the job."
                exit 1
              fi
            fi
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw-escape:
                  - ../../../scripts/build_utils.sh
                  - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false

- job-template:
    name: 'ceph-ansible-prs-{distribution}-{deployment}-{scenario}'
    id: 'ceph-ansible-prs-common-trigger'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{distribution}-{deployment}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: '^jenkins test {distribution}-{deployment}-{scenario}|jenkins test all.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {distribution}-{deployment}-{scenario}"
          started-status: "Running: {distribution}-{deployment}-{scenario}"
          success-status: "OK - {distribution}-{deployment}-{scenario}"
          failure-status: "FAIL - {distribution}-{deployment}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            DISTRIBUTION={distribution}
            DEPLOYMENT={deployment}
            SCENARIO={scenario}
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            # Returns 1 if only .rst and README files were modified
            echo "Checking if only rst and READMEs were modified"
            git show HEAD | grep -qo ^Merge:
            if [ $? -eq 0 ]; then
              git diff --name-only $(git show HEAD | grep ^Merge: | cut -d ':' -f2) | grep -v '\.rst\|README'
              if [ $? -eq 1 ]; then
                echo "Only docs were modified.  Skipping the rest of the job."
                exit 1
              fi
            fi
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw-escape:
                  - ../../../scripts/build_utils.sh
                  - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false

- job-template:
    name: 'ceph-ansible-prs-{distribution}-{deployment}-{scenario}'
    id: 'ceph-ansible-prs-ubuntu-trigger'
    node: '{slave_labels}'
    concurrent: true
    defaults: global
    display-name: 'ceph-ansible: Pull Requests [{distribution}-{deployment}-{scenario}]'
    quiet-period: 5
    block-downstream: false
    block-upstream: false
    retry-count: 3
    properties:
      - github:
          url: https://github.com/ceph/ceph-ansible
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: '^jenkins test {distribution}-{deployment}-{scenario}|jenkins test all.*'
          only-trigger-phrase: true
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: {distribution}-{deployment}-{scenario}"
          started-status: "Running: {distribution}-{deployment}-{scenario}"
          success-status: "OK - {distribution}-{deployment}-{scenario}"
          failure-status: "FAIL - {distribution}-{deployment}-{scenario}"

    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${{sha1}}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 20
          skip-tag: true
          wipe-workspace: false

    builders:
      - inject:
          properties-content: |
            DISTRIBUTION={distribution}
            DEPLOYMENT={deployment}
            SCENARIO={scenario}
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            # Returns 1 if only .rst and README files were modified
            echo "Checking if only rst and READMEs were modified"
            git show HEAD | grep -qo ^Merge:
            if [ $? -eq 0 ]; then
              git diff --name-only $(git show HEAD | grep ^Merge: | cut -d ':' -f2) | grep -v '\.rst\|README'
              if [ $? -eq 1 ]; then
                echo "Only docs were modified.  Skipping the rest of the job."
                exit 1
              fi
            fi
          on-evaluation-failure: dont-run
          steps:
            - shell:
                !include-raw-escape:
                  - ../../../scripts/build_utils.sh
                  - ../../build/build

    publishers:
      - postbuildscript:
          builders:
            - role: SLAVE
              build-on:
                  - FAILURE
                  - ABORTED
              build-steps:
                - shell:
                    !include-raw-escape:
                      - ../../../scripts/build_utils.sh
                      - ../../build/teardown

      - archive:
          artifacts: 'logs/**'
          allow-empty: true
          latest-only: false
