---
# This playbook is used to configure static libvirt&&vagrant slaves.
# Ubuntu >= 16.04 and CentOS 7.3 are the only tested distros
#
# Example usage:
# On a baremetal node already configured by the github.com/ceph/ceph-cm-ansible common role,
# `cd ceph-build/ansible && cp examples/slave_libvirt_static.yml .` then:
# ansible-playbook -M ./library/ slave_libvirt_static.yml --extra-vars '{"token": "XXXXX"}' --limit="yourslave*"

- hosts: all
  become: true
  user: cm
  vars:
   - jenkins_user: 'jenkins-build'
   # jenkins API credentials:
   - api_user: 'ceph-jenkins'
   - jenkins_credentials_uuid: 'f58ac77b-240c-4371-9678-c31389c06728'
   - token: '{{ token }}'
   - api_uri: 'https://2.jenkins.ceph.com'
   - nodename: '{{ ansible_hostname }}'
   - labels: 'vagrant libvirt'

  tasks:

    ### REPO TASKS ###
    - name: Check for custom repos
      shell: "ls -1 /etc/apt/sources.list.d"
      register: custom_repos
      when: ansible_os_family == "Debian"

    - name: Delete custom repos
      file:
        path: "/etc/apt/sources.list.d/{{ item }}"
        state: absent
      with_items: "{{ custom_repos.stdout_lines }}"
      when:
        - custom_repos|length > 0
        - custom_repos is defined
        - ansible_os_family == "Debian"

    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    # vagrant doesn't have repositories, this chacra repo will be better to have
    # around and can get updates as soon as a new vagrant version is published via
    # chacractl
    - name: add the vagrant repository
      apt_repository:
        repo: "deb [trusted=yes] https://chacra.ceph.com/r/vagrant/latest/HEAD/ubuntu/xenial/flavors/default/ xenial main"
        state: present
      when: ansible_os_family == "Debian"

    - name: add the vagrant repository
      yum_repository:
        name: vagrant
        description: self-hosted vagrant repo
        baseurl: https://chacra.ceph.com/r/vagrant/latest/HEAD/centos/7/flavors/default/x86_64/
        enabled: yes
        gpgcheck: no
      when: ansible_os_family == "RedHat"

    - name: disable epel
      lineinfile:
        path: "/etc/yum.repos.d/epel.repo"
        regexp: '^enabled=.*'
        line: 'enabled=0'
      when: ansible_os_family == "RedHat"

    ### PACKAGING TASKS ###
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - python-dev
        - python-pip
        - python-virtualenv
        - libtool
        - libssl-dev
        - libffi-dev
        - debian-archive-keyring
        - libyaml-dev
        - qemu-kvm
        - libvirt-bin
        - libvirt-dev
        - vagrant
        - default-jdk
        - default-jre
      when: ansible_os_family == "Debian"

    - name: install requirements without epel
      yum:
        name: "{{ item }}"
        state: present
        disablerepo: epel
        update_cache: yes
      with_items:
        - git
        - gcc
        - python-devel
        - libffi-devel
        - java-1.8.0-openjdk-devel
        - qemu-kvm
        - libvirt-devel
        - libguestfs
        - libvirt
        - libguestfs-tools
        - vagrant
        - wget
        - curl
        - python-virtualenv
        - openssl-devel
        - redhat-lsb-core
      when: ansible_os_family == "RedHat"

    - name: install packages from epel
      yum:
        name: "{{ item }}"
        state: present
        enablerepo: epel
        update_cache: yes
      with_items:
        - jq
        - python-pip
      when: ansible_os_family == "RedHat"

    ### COMMON TASKS ###
    - set_fact:
        jenkins_group: 'libvirtd'
      when: ansible_distribution_version == '16.04'

    - set_fact:
        jenkins_group: 'libvirt'
      when: (ansible_distribution_version == '16.10') or
            (ansible_distribution_major_version >= 17) or
            (ansible_os_family == "RedHat")

    - name: "create a {{ jenkins_user }} user"
      user:
        name: "{{ jenkins_user }}"
        groups: "{{ jenkins_group }}"
        append: yes
        comment: "Jenkins Build Slave User"

    - name: "create a {{ jenkins_user }} home directory"
      file:
        path: "/home/{{ jenkins_user }}/"
        state: directory
        owner: "{{ jenkins_user }}"

    - name: Create .ssh directory
      file:
        path: "/home/{{ jenkins_user }}/.ssh"
        state: directory
        owner: "{{ jenkins_user }}"

    - name: install the vagrant-libvirt plugin
      shell: vagrant plugin install vagrant-libvirt
      become: yes
      become_user: "{{ jenkins_user }}"

    - name: set the authorized keys
      authorized_key:
        user: "{{ jenkins_user }}"
        key: "{{ lookup('file', 'files/ssh/keys/jenkins_build.pub') }}"

    - name: "ensure {{ jenkins_user }} can sudo without a prompt"
      lineinfile:
        dest: /etc/sudoers
        regexp: '^{{ jenkins_user }} ALL'
        line: '{{ jenkins_user }}   ALL=(ALL:ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: set utf-8 for LC_ALL
      lineinfile:
        dest: "/home/{{ jenkins_user }}/.bashrc"
        regexp: '^export LC_ALL='
        line: "export LC_ALL=en_US.UTF-8"
        create: true
        state: present

    - name: set utf-8 for LANG
      lineinfile:
        dest: "/home/{{ jenkins_user }}/.bashrc"
        regexp: '^export LANG='
        line: "export LANG=en_US.UTF-8"

    - name: set utf-8 for LANGUAGE
      lineinfile:
        dest: "/home/{{ jenkins_user }}/.bashrc"
        regexp: '^export LANGUAGE='
        line: "export LANGUAGE=en_US.UTF-8"

    - name: ensure the build dir exists
      file:
        path: "/home/{{ jenkins_user }}/build"
        state: directory
        owner: "{{ jenkins_user }}"

    - name: ensure the home dir has the right owner permissions
      file:
        path: "/home/{{ jenkins_user }}"
        state: directory
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        recurse: yes

    # Makes sure only our block is in the file
    - name: remove gitconfig file
      file:
        path: "/home/{{ jenkins_user }}/.gitconfig"
        state: absent

    - name: ensure our gitconfig file exists
      blockinfile:
        dest: "/home/{{ jenkins_user }}/.gitconfig"
        create: yes
        owner: "{{ jenkins_user }}"
        group: "{{ jenkins_user }}"
        block: |
          [user]
          name=Ceph CI
          email=ceph-release-team@redhat.com

    - name: Set Hostname with hostname command
      hostname:
        name: "{{ ansible_hostname }}"

    - name: ensure that the current host is in /etc/hosts. Yes this is a thing.
      replace:
        backup: yes
        dest: /etc/hosts
        regexp: '^(127\.0\.1\.1(?!.*\b{{ ansible_hostname }}\b).*)$'
        replace: '\1 {{ ansible_hostname }}'

    - name: install six, latest one
      pip:
        name: six
        state: latest

    - name: install python-jenkins
      # https://review.openstack.org/460363
      pip:
        name: python-jenkins
        version: 0.4.15

    - name: add github.com host key
      known_hosts:
        path: '/etc/ssh/ssh_known_hosts'
        # we need to use 'host' here because prado currently uses ansible-playbook==1.9.1
        host: 'github.com'
        # github.com.pub is the output of `ssh-keyscan github.com`
        key: "{{ lookup('file', 'files/ssh/hostkeys/github.com.pub') }}"

    ### LIBVIRT TASKS ###
    - name: "configure libvirt permissions for {{ jenkins_user }}"
      blockinfile:
        dest: /etc/libvirt/qemu.conf
        block: |
          user = "{{ jenkins_user }}"
          group = "{{ jenkins_user }}"
      when: ansible_os_family == "RedHat"

    - name: start DEB libvirt services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - libvirt-bin
        - libvirt-guests
      when: ansible_os_family == "Debian"

    - name: start RPM libvirt services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - libvirtd
        - libvirt-guests
      when: ansible_os_family == "RedHat"

    ### JENKINS TASKS ###
    - name: register the new slave to jenkins master with jnlp
      jenkins_node:
        username: "{{ api_user }}"
        uri: "{{ api_uri }}"
        password: "{{ token }}"
        # relies on a convention to set a unique name that allows a reverse
        # mapping from Jenkins back to whatever service created the current
        # node
        name: "{{ ansible_default_ipv4.address }}+{{ nodename }}"
        labels: "{{ labels }}"
        host: "{{ ansible_default_ipv4.address }}"
        credentialsId: "{{ jenkins_credentials_uuid }}"
        launcher: 'hudson.slaves.JNLPLauncher'
        remoteFS: '/home/{{ jenkins_user }}/build'
        # XXX this should be configurable, not all nodes should have one executor
        executors: '{{ executors|default(1) }}'
        exclusive: true

    - name: Download slave.jar
      get_url:
        url: "{{ api_uri }}/jnlpJars/slave.jar"
        dest: "/home/{{ jenkins_user }}/slave.jar"

    - name: install the systemd unit file for jenkins
      template:
        src: "templates/systemd/jenkins.service.j2"
        dest: "/etc/systemd/system/jenkins.service"

    - name: start jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
