- job:
    name: ceph-ansible-pipeline
    description: 'This is the main ceph-ansible job that triggers the linter, docs, and scenario jobs'
    node: master
    project-type: multijob
    defaults: global
    concurrent: true
    display-name: 'ceph-ansible PR Pipeline Job'
    block-downstream: false
    block-upstream: false
    properties:
      - build-discarder:
          days-to-keep: 90
          num-to-keep: -1
          artifact-days-to-keep: -1
          artifact-num-to-keep: -1
      - github:
          url: https://github.com/ceph/ceph-ansible

    parameters:
      - string:
          name: sha1
          description: "A pull request ID, like 'origin/pr/72/head'"

    triggers:
      - github-pull-request:
          cancel-builds-on-update: true
          allow-whitelist-orgs-as-admins: true
          org-list:
            - ceph
          skip-build-phrase: '^jenkins do not test.*|.*\[skip ci\].*'
          trigger-phrase: 'jenkins test pipeline'
          only-trigger-phrase: false
          github-hooks: true
          permit-all: true
          auto-close-on-fail: false
          status-context: "Testing: ceph-ansible PR Pipeline"
          started-status: "Running: ceph-ansible PR Pipeline"
          success-status: "OK - ceph-ansible PR Pipeline"
          failure-status: "FAIL - A sub-job in the Pipeline failed"

# Surely there's a saner way to do this but it works...
# The 'included/excluded regions' parameters for the Git plugin could've been
# used in ceph-ansible-prs.yml but https://issues.jenkins-ci.org/browse/JENKINS-20607
    builders:
      - multijob:
          name: 'ceph-ansible docs and syntax check phase'
          condition: SUCCESSFUL
          execution-type: PARALLEL
          projects:
            - name: ceph-ansible-docs-pull-requests
              current-parameters: true
            - name: ceph-ansible-pr-syntax-check
              current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/add-osd'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible purge playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-add_osds'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-add_osds_container'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            # if the current branch is master then we don't run these tests
            if [[ "$ghprbTargetBranch" == "master" ]]; then
              exit 1
            fi
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/purge'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible purge playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-purge_bluestore_osds_non_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-purge_cluster_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-purge_cluster_non_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-purge_filestore_osds_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-purge_filestore_osds_non_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-purge_lvm_osds'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            # if the current branch is stable-3.0 or stable-3.1 then we don't run these tests
            if [[ "$ghprbTargetBranch" == "stable-3.1" ]] || [[ "$ghprbTargetBranch" == "stable-3.0" ]]; then
              exit 1
            fi
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/purge'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible purge playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-purge_lvm_osds'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/rolling_update'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible rolling_update playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-update_cluster'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-update_docker_cluster'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/shrink-mon'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible shrink_mon playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-shrink_mon'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-shrink_mon_container'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/shrink-osd'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible shrink_osd playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-shrink_osd'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-shrink_osd_container'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep 'infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible switch_to_containers playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-switch_to_containers'
                    current-parameters: true
      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            # if the current branch is master then we don't run these tests
            if [[ "$ghprbTargetBranch" == "master" ]]; then
              exit 1
            fi
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep -E 'roles/ceph-defaults/tasks/facts.yml|roles/ceph-osd|ceph-validate'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible osd scenarios playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-bluestore_lvm_osds'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-bluestore_osds_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-bluestore_osds_non_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-filestore_osds_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-filestore_osds_non_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-lvm_osds'
                    current-parameters: true

      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            # if the current branch is stable-3.0 or stable-3.1 then we don't run these tests
            if [[ "$ghprbTargetBranch" == "stable-3.1" ]] || [[ "$ghprbTargetBranch" == "stable-3.0" ]]; then
              exit 1
            fi
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep -E 'roles/ceph-defaults/tasks/facts.yml|roles/ceph-osd|ceph-validate'
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible osd scenarios playbook testing'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-lvm_osds'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-lvm_osds_container'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-bluestore_lvm_osds'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-bluestore_lvm_osds_container'
                    current-parameters: true
                  #- name: 'ceph-ansible-prs-luminous-lvm_batch'
                  #  current-parameters: true
                  # lvm batch container is not supported at the moment, see https://tracker.ceph.com/issues/36363
                  #- name: 'ceph-ansible-prs-luminous-lvm_batch_container'
                  #  current-parameters: true

      - conditional-step:
          condition-kind: shell
          condition-command: |
            #!/bin/bash
            set -x
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep -v 'infrastructure-playbooks'
            if [ $? -eq 1 ]; then
              echo "Infra playbooks modified.  Not testing remaining scenarios."
              exit 1
            fi
            # do not run if roles/ceph-osd has been touched since the task above play osds already
            git diff --name-only $(git show HEAD | grep Merge | head -n 1 | cut -d ':' -f2) | grep -E 'roles/ceph-osd'
            if [ $? -eq 0 ]; then
              echo "ceph-osd role modified, nothing to test, the ceph-osd role test is handled by another pipeline job."
              exit 1
            fi
          on-evaluation-failure: dont-run
          steps:
            - multijob:
                name: 'ceph-ansible basic cluster testing phase'
                condition: SUCCESSFUL
                execution-type: PARALLEL
                projects:
                  - name: 'ceph-ansible-prs-luminous-centos7_cluster'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-docker_cluster'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-docker_cluster_collocation'
                    current-parameters: true
                  - name: 'ceph-ansible-prs-luminous-ooo_collocation'
                    current-parameters: true
    scm:
      - git:
          url: https://github.com/ceph/ceph-ansible.git
          branches:
            - ${sha1}
          refspec: +refs/pull/*:refs/remotes/origin/pr/*
          browser: auto
          timeout: 60
          skip-tag: true
          wipe-workspace: false

    wrappers:
      - inject-passwords:
          global: true
          mask-password-params: true
