
  - name: set the debian version
    command: dch -v {{ version }}-1 -D stable "New upstream release" chdir=ceph
    environment:
      DEBEMAIL: "{{ debemail }}"
      DEBFULLNAME: "{{ debfullname }}"
